name: ci

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [master]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry install
      - run: poetry run flake8
      - run: poetry run black --line-length 120 --check .
      - run: poetry run isort --check --line-length 120 --profile black .
      - run: poetry run xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: poetry run mypy azure_oidc
  create_tag_release:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: create_tag_release
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry self add "poetry-dynamic-versioning[plugin]"
      - run: poetry config repositories.azure https://pkgs.dev.azure.com/binkhq/_packaging/binkhq/pypi/upload/
      - run: poetry config http-basic.azure jeff ${{ secrets.AZURE_DEVOPS_PAT }}
      - run: poetry build
      - run: poetry publish -r azure
